--DROP TABLE ORGANIZATION;
--DROP TABLE EVENT;
--DROP TABLE PARTICIPANT;
--DROP TABLE SCAN;

CREATE TABLE ORGANIZATION(
	ORGANIZATION_ID INT PRIMARY KEY,
	ORGANIZATION_NAME VARCHAR(45) NOT NULL,
	ORGANIZATION_SPONSOR VARCHAR(45)
);


CREATE TABLE EVENT(
	EVENT_ID INT PRIMARY KEY,
	ORGANIZATION_ID INT NOT NULL,
	EVENT_NAME VARCHAR(45) NOT NULL,
	EVENT_LOCATION VARCHAR(45) NOT NULL,
	EVENT_DATE DATE,
	EVENT_COORDINATOR VARCHAR(45) NOT NULL,
	EVENT_EMAIL VARCHAR(60) NOT NULL,
	EVENT_LOGO VARCHAR(100),
	EVENT_MAINCOLOR VARCHAR(20),
	EVENT_TEXTCOLOR VARCHAR(7),
	EVENT_HEADERCOLOR VARCHAR(20),
	FOREIGN KEY(ORGANIZATION_ID) REFERENCES ORGANIZATION(ORGANIZATION_ID)
);

CREATE TABLE PARTICIPANT(
	PARTICIPANT_ID INT PRIMARY KEY,
	Type INT NOT NULL,
	PARTICIPANT_LNAME VARCHAR(45) NOT NULL,
	PARTICIPANT_FNAME VARCHAR(45) NOT NULL,
	PARTICIPANT_EMAIL VARCHAR(60) NOT NULL,
	Major VARCHAR(100),
	QRCODE VARCHAR(10) NOT NULL,
	PARTICIPANT_PICTURE VARCHAR(100),
	FOREIGN KEY(EVENT_ID) REFERENCES EVENT(EVENT_ID)
);

CREATE TABLE SCAN(
	PARTICIPANT_ID INT,
	QR_SCANNED VARCHAR(10) NOT NULL,
	SCAN_TIME DATETIME NOT NULL,
	PRIMARY KEY(PARTICIPANT_ID, QR_SCANNED),
	FOREIGN KEY(PARTICIPANT_ID) REFERENCES PARTICIPANT(PARTICIPANT_ID)
);